### ISSUE TITLE
Upgrade to Gradle 7.1 fails

### ISSUE THREAD

**Issue by binkley** [aalmiray/jdeps-gradle-plugin#19] opened 2021-06-16 03:06 UTC
I'm seeing this when moving to Gradle 7.1 from 7.0.2:
```
* What went wrong:
Execution failed for task ':jdepsReport'.
> Configuration with name 'runtime' not found.
```
My only configuration in `build.gradle` is:
```
jdepsReport {
    multiReleaseJars = [".*": "$jdkVersion"]
}
```
I don't have multi-release jars, but some dependencies do.

**Comment by aalmiray** [comment] 2021-06-16 09:23
Probable duplicate of https://github.com/kordamp/jdeps-gradle-plugin/issues/17

**Closed as completed** 2021-06-16 12:23 UTC
Labels: bug
